### PR TITLE
[WIP] PPO parameters for Robosuite

### PR DESCRIPTION
**Pull request by jcreus**
This pull requests updates the parameters for Robosuite. Preliminary benchmarks on some of the Robosuite environments look good; missing an environment + running experiments with pixel_input. The same set of parameters, running on states with 4 agents (on a Ryzen 2700X + GTX1060), achieves the following results:
- SawyerStack, 650 in 7 hours.
- SawyerLift, 400+ in 3 hours. A more aggressive version of the parameters can do it in 2h20min.
- SawyerPickAndPlace, 620 in 17 hours. It was still slowly improving but one of the threads crashed.
- BaxterLift, 450 in 3 hours.

These results seem comparable or better than the 16 agent version as published in the CoRL paper. However, that was on a distributed platform, and the specs might not necessarily be comparable.

One important thing I think we should have a workaround for is episode lengths. Right now the ppo_configs.py file has to be changed for each different experiment, since they have different episode lengths. In Gym, episode length is simply set to 0, and the environment finishes when the maximum number of steps is reached. Something like that would be valuable for Robosuite.

### CODE REVIEW

**Comment by LinxiFan** [comment]
This is great, thanks for your efforts Joan!
Could you please write up this as a separate doc in a new file `docs/performance.md`?

**Comment by kapsl** [comment]
For me and on my experiment this does still not really make ppo much better (but faster). But still ddpg reaches a much better performance.

**Comment by jcreus** [comment]
@kapsi What environment are you trying this on? These parameters were tuned for the Robosuite environments - Gym environments, for instance, are different enough to want different params (I'll upload a set of parameters for that soon).

**Comment by kapsl** [comment]
It's an own environment that could also be executed on a real robot. Do you do some kind of systematic hyperpatameter search?

**Comment by jcreus** [comment]
@kapsl The search was more ad hoc, going through hyperparameters that appeared to be most important. It will probably depend a fair amount on your environment, but if you have the resources, it would be probably easiest to set them up to run automatically. At some point I'll try to dig up a script I used earlier to launch experiments in series a while back; since I was computationally limited this time, I mostly just did it by hand.

@LinxiFan the latest commit adds a set of parameters for HalfCheetah and Hopper. As I showed you earlier, the training is kind of noisy - I think this is a combination of the fact that I'm using 4 (instead of >= 16) agents, and perhaps some more tuning that would make the training nicer. Regardless, this set of parameters for Gym achieves 6,100 in two hours for HalfCheetah (on 4 agents), and, on Hopper, a high score on eval 3270 in three and a half hours (also on 4 agents). It would be good to at some point iterate a bit to try to get the learning noise down, but for now these are better than the ones posted in the repo, I believe.

**Comment by LinxiFan** [comment]
LGTM!

**Pull request merged**
